/** Declaration file generated by dts-gen */

export = extract_css_chunks_webpack_plugin;

declare class extract_css_chunks_webpack_plugin {
    constructor(...args: any[]);

    apply(...args: any[]): void;

    getCssChunkObject(...args: any[]): void;

    renderContentAsset(...args: any[]): void;

    static loader: string;

}

